### PR TITLE
Upgrade from py36 to py37 to fix CI test error

### PR DESCRIPTION
**Pull request by edingroot**
CI error:  
image

Reproduced and tested in devbox.

### CODE REVIEW

**Comment by 88manpreet** [comment]
For this scope of change, please add someone from Compute Infra

**Comment by edingroot** [comment]
Hi @nemacysts, can you please help to review the python version change of this repo? The jenkins job for updating internal pypi failed due to version conflict: https://jenkins-george.yelpcorp.com/blue/organizations/jenkins/mirrors-Yelp-service_configuration_lib-python/detail/mirrors-Yelp-service_configuration_lib-python/617/pipeline/64

**Review by nemacysts — APPROVED** [review]
this looks like it should be fine - seems like all the python packages that dep this one are already only testing on py37+, so this shouldn't negatively impact anyone if we start to use any py37+ features in this repo

**Comment by nemacysts** [comment]
that said, we could also add some upper-bounds to the "problematic" dependencies if you don't want to raise the minimum required python version for this package

**Pull request merged**
